### ISSUE TITLE
status 通常表示终态，用state可能会有误解

### ISSUE THREAD

**Issue by Quanzhitong** [cangSDARM/react-query-web-i18n#6]
#### 为什么有两种表示状态的东西(status/fetchStatus)？
   * 一个state='success'的查询通常处于fetchStatus='idle'状态。但如果同时有后台重新获取动作，它也可能为fetchStatus='fetching'状态。 （这里的state，应该是status）

**Comment by cangSDARM** [comment]
这个没问题。
![image](https://user-images.githubusercontent.com/20441896/202640142-945466b6-ac68-419c-a3f5-77d8ac6b298c.png)
官方文档也是用的同样的state/status。
只是处于阅读流畅性考虑，用到了 `state='success'` 的写法，而不是直译 `success的state`
